server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

  redis:
    # database: 2
    host: localhost
    port: 6379
    password:
#    jedis:
#      pool:
#        max-active: 500
#        max-wait: 500
#        min-idle: 0
#        max-idle: 500
#      time-out: 500

  application:
    name: nacos-server
  cloud:
    nacos:
      discovery:
        server-addr: 10.11.32.195:8848

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.itjizhiyong.entities
  configuration:
    map-underscore-to-camel-case: true

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  datasource:
#    druid:
#      #本地数据源
#      mysql:
#        #数据库访问配置
#        url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: root
#        #连接池配置
#        initial-size: 5 #默认连接数
#        min-idle: 5 #最小连接数
#        #max-idle: 10 已经弃用
#        max-wait: 30000 #连接等待超时时间
#        time-between-eviction-runs-millis: 60000 #配置检测可以关闭的空间连接间隔时间
#        min-eviction-idle-time-millis: 30000 #连接在池中最小生存时间
#        validationQuery: select 1 #用于验证数据库连接是否有效 oracle为select 1 from dual
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
#        filters: stat,wall
#        # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#        aop-patterns: com.Lirs.Spring.controller.*
#      # StatViewServlet配置 用于提供展示监控信息的html页面、JSON API
#      stat-view-servlet:
#        enabled: true
#        # 访问路径为/druid时，跳转到StatViewServlet
#        url-pattern: /druid/*
#        # 是否能够重置数据
#        reset-enable: false
#        # 需要账号密码才能访问控制台
#        login-username: admin
#        login-password: 960215@Xiaozhen
#      # IP白名单
#      # allow: 127.0.0.1
#      #　IP黑名单（共同存在时，deny优先于allow）
#      # deny: 192.168.1.218
#      # WebStatFilter配置 用于url统计 这点之后做补充学习
#      web-stat-filter:
#        enabled: true
#        # 添加过滤规则
#        url-pattern: /*
#        # 忽略过滤的格式
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      #打开PSCache,并且指定每个连接上PSCache的大小  这个地方之后需要补充学习
#      pool-prepared-statements: true
#      max-open-prepared-statements: 20
#      max-pool-prepared-statement-per-connection-size: 20

feign:
  sentinel:
    enable: true